### ISSUE TITLE
why drop the last token?

### ISSUE THREAD

**Issue by maxin-cn** [hp-l33/AiM#11]
Thank you open-source this great work!

I’ve read through your code and have a question here. Why do you discard the last token of the image? Wouldn’t this lead to a drop in performance?

https://github.com/hp-l33/AiM/blob/0a91c608723102074d785bf442167db71092d0aa/models/aim.py#L47

**Comment by hp-l33** [comment]
Hi,

Dropping the last token is a left shift of the input, aiming to construct teacher forcing training data. Specifically, the model predicts the next token based on the current token and all previous tokens.

For example, if we take 0, 1, 2, 3, 4 as the target labels, the input data should be C, 0, 1, 2, 3, where C is the class embedding. Since we directly concatenate C to the left of the target, it is necessary to drop the last token of the target accordingly.
```
target: 0, 1, 2, 3, 4
input : C, 0, 1, 2, 3
```

**Comment by maxin-cn** [comment]
Thanks! I got it.
